# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public_search.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13public_search.proto\x12\rpublic_search\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xf6\x01\n\x07Greeter\x12\x44\n\x08SayHello\x12\x1b.public_search.HelloRequest\x1a\x19.public_search.HelloReply\"\x00\x12Q\n\x13SayHelloStreamReply\x12\x1b.public_search.HelloRequest\x1a\x19.public_search.HelloReply\"\x00\x30\x01\x12R\n\x12SayHelloBidiStream\x12\x1b.public_search.HelloRequest\x1a\x19.public_search.HelloReply\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'public_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=38
  _globals['_HELLOREQUEST']._serialized_end=66
  _globals['_HELLOREPLY']._serialized_start=68
  _globals['_HELLOREPLY']._serialized_end=97
  _globals['_GREETER']._serialized_start=100
  _globals['_GREETER']._serialized_end=346
# @@protoc_insertion_point(module_scope)
